<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-08T13:29:25Z" name="Default suite" finished-at="2022-10-08T13:30:14Z" duration-ms="48856">
    <groups>
    </groups>
    <test started-at="2022-10-08T13:29:25Z" name="Default test" finished-at="2022-10-08T13:30:14Z" duration-ms="48856">
      <class name="org.e_banking.testStep.TC1">
        <test-method is-config="true" signature="browser()[pri:0, instance:org.e_banking.testStep.TC1@5adb0db3]" started-at="2022-10-08T18:59:25Z" name="browser" finished-at="2022-10-08T18:59:31Z" duration-ms="6157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser -->
        <test-method signature="SM1()[pri:0, instance:org.e_banking.testStep.TC1@5adb0db3]" started-at="2022-10-08T18:59:31Z" name="SM1" finished-at="2022-10-08T19:00:14Z" duration-ms="42667" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Password is changed] but found [Please fill all fields]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Password is changed] but found [Please fill all fields]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at org.e_banking.testStep.TC1.SM1(TC1.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SM1 -->
      </class> <!-- org.e_banking.testStep.TC1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
